#!/bin/sh -e
#export

start_dir="$(pwd)"
cd "$(dirname "$0")"
program_dir="$(pwd)"

. ./common.sh

if [ -z "$SMLB_LOADINGTIME" ]; then
    # default loading time, is substracted from maxExecutionTime
    SMLB_LOADINGTIME=10
fi
if [ -n "$SMLB_TOOL_MAXEXECUTIONTIME" ]; then
    maxExecutionTime="$SMLB_TOOL_MAXEXECUTIONTIME"
else
    maxExecutionTime="$(($SMLB_MAXEXECUTIONTIME-$SMLB_LOADINGTIME))"
fi

common_config

add_conf
add_conf "$algorithm_const.writeSearchTree" '=' false

add_conf "$algorithm_const.maxExecutionTimeInSeconds" '=' "$maxExecutionTime"

$dllearner_file "$conf" | tee "$tmpdir"/output.log
#cp "$tmpdir"/output.log test.log
# we only check the first result for the benchmark
sed '0,/^solutions:/d' "$tmpdir"/output.log | grep '^1: ' \
   | sed -e 's,^1: ,,' -e 's, ([^)]*)$,,' > "$result_output_file"

#cat "$conf"
