#!/bin/sh -e
#export

start_dir="$(pwd)"
cd "$(dirname "$0")"
program_dir="$(pwd)"

. ./common.sh

add_conf cli.type '=' '"org.dllearner.cli.ExpressionValidation"'
# we need to escape \" with %22 for the dllearner config parser
add_conf cli.expression '=' '"'"$(cat "$SMLB_FILENAME_INPUT" | sed -e 's.".%22.g')"'"'
add_conf

common_config

add_conf
add_conf acc.type '=' '"gen_fmeasure"'

$dllearner_file "$conf" | tee "$tmpdir"/output.log
#cp "$tmpdir"/output.log test.log
# we only check the first result for the benchmark
grep '#EVAL#' "$tmpdir"/output.log \
   | sed -e 's,^#EVAL# ,,' > "$result_output_file"

#cat "$conf"
