ex('mammographic:Patient0').
ex('mammographic:Patient1').
ex('mammographic:Patient10').
ex('mammographic:Patient106').
ex('mammographic:Patient109').
ex('mammographic:Patient11').
ex('mammographic:Patient111').
ex('mammographic:Patient118').
ex('mammographic:Patient120').
ex('mammographic:Patient129').
ex('mammographic:Patient130').
ex('mammographic:Patient131').
ex('mammographic:Patient134').
ex('mammographic:Patient135').
ex('mammographic:Patient136').
ex('mammographic:Patient137').
ex('mammographic:Patient139').
ex('mammographic:Patient140').
ex('mammographic:Patient145').
ex('mammographic:Patient146').
ex('mammographic:Patient147').
ex('mammographic:Patient148').
ex('mammographic:Patient150').
ex('mammographic:Patient151').
ex('mammographic:Patient156').
ex('mammographic:Patient159').
ex('mammographic:Patient160').
ex('mammographic:Patient165').
ex('mammographic:Patient166').
ex('mammographic:Patient168').
ex('mammographic:Patient169').
ex('mammographic:Patient17').
ex('mammographic:Patient175').
ex('mammographic:Patient179').
ex('mammographic:Patient18').
ex('mammographic:Patient184').
ex('mammographic:Patient185').
ex('mammographic:Patient186').
ex('mammographic:Patient188').
ex('mammographic:Patient189').
ex('mammographic:Patient191').
ex('mammographic:Patient193').
ex('mammographic:Patient195').
ex('mammographic:Patient197').
ex('mammographic:Patient2').
ex('mammographic:Patient20').
ex('mammographic:Patient202').
ex('mammographic:Patient205').
ex('mammographic:Patient207').
ex('mammographic:Patient21').
ex('mammographic:Patient212').
ex('mammographic:Patient213').
ex('mammographic:Patient214').
ex('mammographic:Patient222').
ex('mammographic:Patient223').
ex('mammographic:Patient224').
ex('mammographic:Patient226').
ex('mammographic:Patient23').
ex('mammographic:Patient231').
ex('mammographic:Patient232').
ex('mammographic:Patient234').
ex('mammographic:Patient238').
ex('mammographic:Patient24').
ex('mammographic:Patient240').
ex('mammographic:Patient244').
ex('mammographic:Patient247').
ex('mammographic:Patient25').
ex('mammographic:Patient251').
ex('mammographic:Patient253').
ex('mammographic:Patient254').
ex('mammographic:Patient256').
ex('mammographic:Patient257').
ex('mammographic:Patient258').
ex('mammographic:Patient259').
ex('mammographic:Patient260').
ex('mammographic:Patient264').
ex('mammographic:Patient266').
ex('mammographic:Patient268').
ex('mammographic:Patient269').
ex('mammographic:Patient270').
ex('mammographic:Patient271').
ex('mammographic:Patient272').
ex('mammographic:Patient274').
ex('mammographic:Patient276').
ex('mammographic:Patient278').
ex('mammographic:Patient28').
ex('mammographic:Patient280').
ex('mammographic:Patient283').
ex('mammographic:Patient284').
ex('mammographic:Patient285').
ex('mammographic:Patient288').
ex('mammographic:Patient290').
ex('mammographic:Patient292').
ex('mammographic:Patient293').
ex('mammographic:Patient295').
ex('mammographic:Patient297').
ex('mammographic:Patient299').
ex('mammographic:Patient300').
ex('mammographic:Patient31').
ex('mammographic:Patient310').
ex('mammographic:Patient311').
ex('mammographic:Patient312').
ex('mammographic:Patient313').
ex('mammographic:Patient315').
ex('mammographic:Patient319').
ex('mammographic:Patient32').
ex('mammographic:Patient320').
ex('mammographic:Patient321').
ex('mammographic:Patient323').
ex('mammographic:Patient328').
ex('mammographic:Patient329').
ex('mammographic:Patient330').
ex('mammographic:Patient332').
ex('mammographic:Patient333').
ex('mammographic:Patient335').
ex('mammographic:Patient336').
ex('mammographic:Patient337').
ex('mammographic:Patient338').
ex('mammographic:Patient340').
ex('mammographic:Patient341').
ex('mammographic:Patient345').
ex('mammographic:Patient347').
ex('mammographic:Patient350').
ex('mammographic:Patient351').
ex('mammographic:Patient354').
ex('mammographic:Patient357').
ex('mammographic:Patient358').
ex('mammographic:Patient360').
ex('mammographic:Patient361').
ex('mammographic:Patient363').
ex('mammographic:Patient367').
ex('mammographic:Patient368').
ex('mammographic:Patient369').
ex('mammographic:Patient37').
ex('mammographic:Patient370').
ex('mammographic:Patient374').
ex('mammographic:Patient375').
ex('mammographic:Patient377').
ex('mammographic:Patient379').
ex('mammographic:Patient38').
ex('mammographic:Patient381').
ex('mammographic:Patient382').
ex('mammographic:Patient385').
ex('mammographic:Patient390').
ex('mammographic:Patient391').
ex('mammographic:Patient395').
ex('mammographic:Patient396').
ex('mammographic:Patient399').
ex('mammographic:Patient4').
ex('mammographic:Patient401').
ex('mammographic:Patient403').
ex('mammographic:Patient404').
ex('mammographic:Patient405').
ex('mammographic:Patient406').
ex('mammographic:Patient409').
ex('mammographic:Patient411').
ex('mammographic:Patient413').
ex('mammographic:Patient414').
ex('mammographic:Patient415').
ex('mammographic:Patient417').
ex('mammographic:Patient418').
ex('mammographic:Patient419').
ex('mammographic:Patient420').
ex('mammographic:Patient424').
ex('mammographic:Patient426').
ex('mammographic:Patient428').
ex('mammographic:Patient429').
ex('mammographic:Patient431').
ex('mammographic:Patient433').
ex('mammographic:Patient434').
ex('mammographic:Patient435').
ex('mammographic:Patient436').
ex('mammographic:Patient437').
ex('mammographic:Patient439').
ex('mammographic:Patient44').
ex('mammographic:Patient440').
ex('mammographic:Patient441').
ex('mammographic:Patient443').
ex('mammographic:Patient444').
ex('mammographic:Patient445').
ex('mammographic:Patient448').
ex('mammographic:Patient449').
ex('mammographic:Patient45').
ex('mammographic:Patient450').
ex('mammographic:Patient453').
ex('mammographic:Patient456').
ex('mammographic:Patient457').
ex('mammographic:Patient458').
ex('mammographic:Patient46').
ex('mammographic:Patient462').
ex('mammographic:Patient466').
ex('mammographic:Patient467').
ex('mammographic:Patient469').
ex('mammographic:Patient471').
ex('mammographic:Patient478').
ex('mammographic:Patient480').
ex('mammographic:Patient487').
ex('mammographic:Patient488').
ex('mammographic:Patient49').
ex('mammographic:Patient490').
ex('mammographic:Patient491').
ex('mammographic:Patient492').
ex('mammographic:Patient493').
ex('mammographic:Patient494').
ex('mammographic:Patient495').
ex('mammographic:Patient496').
ex('mammographic:Patient499').
ex('mammographic:Patient501').
ex('mammographic:Patient506').
ex('mammographic:Patient507').
ex('mammographic:Patient508').
ex('mammographic:Patient509').
ex('mammographic:Patient51').
ex('mammographic:Patient512').
ex('mammographic:Patient513').
ex('mammographic:Patient514').
ex('mammographic:Patient517').
ex('mammographic:Patient520').
ex('mammographic:Patient521').
ex('mammographic:Patient522').
ex('mammographic:Patient525').
ex('mammographic:Patient526').
ex('mammographic:Patient527').
ex('mammographic:Patient529').
ex('mammographic:Patient535').
ex('mammographic:Patient537').
ex('mammographic:Patient538').
ex('mammographic:Patient54').
ex('mammographic:Patient543').
ex('mammographic:Patient544').
ex('mammographic:Patient547').
ex('mammographic:Patient548').
ex('mammographic:Patient549').
ex('mammographic:Patient550').
ex('mammographic:Patient554').
ex('mammographic:Patient557').
ex('mammographic:Patient559').
ex('mammographic:Patient560').
ex('mammographic:Patient564').
ex('mammographic:Patient565').
ex('mammographic:Patient569').
ex('mammographic:Patient575').
ex('mammographic:Patient578').
ex('mammographic:Patient583').
ex('mammographic:Patient588').
ex('mammographic:Patient589').
ex('mammographic:Patient59').
ex('mammographic:Patient591').
ex('mammographic:Patient592').
ex('mammographic:Patient596').
ex('mammographic:Patient598').
ex('mammographic:Patient599').
ex('mammographic:Patient60').
ex('mammographic:Patient601').
ex('mammographic:Patient602').
ex('mammographic:Patient603').
ex('mammographic:Patient605').
ex('mammographic:Patient606').
ex('mammographic:Patient609').
ex('mammographic:Patient61').
ex('mammographic:Patient610').
ex('mammographic:Patient611').
ex('mammographic:Patient613').
ex('mammographic:Patient614').
ex('mammographic:Patient616').
ex('mammographic:Patient618').
ex('mammographic:Patient623').
ex('mammographic:Patient624').
ex('mammographic:Patient626').
ex('mammographic:Patient633').
ex('mammographic:Patient635').
ex('mammographic:Patient639').
ex('mammographic:Patient64').
ex('mammographic:Patient640').
ex('mammographic:Patient642').
ex('mammographic:Patient646').
ex('mammographic:Patient649').
ex('mammographic:Patient651').
ex('mammographic:Patient653').
ex('mammographic:Patient655').
ex('mammographic:Patient656').
ex('mammographic:Patient659').
ex('mammographic:Patient660').
ex('mammographic:Patient662').
ex('mammographic:Patient663').
ex('mammographic:Patient664').
ex('mammographic:Patient668').
ex('mammographic:Patient67').
ex('mammographic:Patient670').
ex('mammographic:Patient671').
ex('mammographic:Patient672').
ex('mammographic:Patient673').
ex('mammographic:Patient674').
ex('mammographic:Patient675').
ex('mammographic:Patient676').
ex('mammographic:Patient677').
ex('mammographic:Patient678').
ex('mammographic:Patient683').
ex('mammographic:Patient684').
ex('mammographic:Patient685').
ex('mammographic:Patient686').
ex('mammographic:Patient687').
ex('mammographic:Patient688').
ex('mammographic:Patient689').
ex('mammographic:Patient692').
ex('mammographic:Patient693').
ex('mammographic:Patient697').
ex('mammographic:Patient699').
ex('mammographic:Patient700').
ex('mammographic:Patient701').
ex('mammographic:Patient703').
ex('mammographic:Patient705').
ex('mammographic:Patient708').
ex('mammographic:Patient71').
ex('mammographic:Patient712').
ex('mammographic:Patient713').
ex('mammographic:Patient717').
ex('mammographic:Patient718').
ex('mammographic:Patient722').
ex('mammographic:Patient724').
ex('mammographic:Patient726').
ex('mammographic:Patient727').
ex('mammographic:Patient73').
ex('mammographic:Patient730').
ex('mammographic:Patient731').
ex('mammographic:Patient737').
ex('mammographic:Patient74').
ex('mammographic:Patient746').
ex('mammographic:Patient748').
ex('mammographic:Patient752').
ex('mammographic:Patient753').
ex('mammographic:Patient756').
ex('mammographic:Patient757').
ex('mammographic:Patient758').
ex('mammographic:Patient759').
ex('mammographic:Patient76').
ex('mammographic:Patient761').
ex('mammographic:Patient762').
ex('mammographic:Patient763').
ex('mammographic:Patient765').
ex('mammographic:Patient766').
ex('mammographic:Patient769').
ex('mammographic:Patient772').
ex('mammographic:Patient774').
ex('mammographic:Patient78').
ex('mammographic:Patient782').
ex('mammographic:Patient783').
ex('mammographic:Patient785').
ex('mammographic:Patient787').
ex('mammographic:Patient788').
ex('mammographic:Patient791').
ex('mammographic:Patient792').
ex('mammographic:Patient795').
ex('mammographic:Patient796').
ex('mammographic:Patient797').
ex('mammographic:Patient799').
ex('mammographic:Patient8').
ex('mammographic:Patient800').
ex('mammographic:Patient801').
ex('mammographic:Patient805').
ex('mammographic:Patient806').
ex('mammographic:Patient808').
ex('mammographic:Patient81').
ex('mammographic:Patient810').
ex('mammographic:Patient811').
ex('mammographic:Patient812').
ex('mammographic:Patient814').
ex('mammographic:Patient82').
ex('mammographic:Patient820').
ex('mammographic:Patient823').
ex('mammographic:Patient824').
ex('mammographic:Patient826').
ex('mammographic:Patient827').
ex('mammographic:Patient829').
ex('mammographic:Patient830').
ex('mammographic:Patient832').
ex('mammographic:Patient833').
ex('mammographic:Patient835').
ex('mammographic:Patient837').
ex('mammographic:Patient84').
ex('mammographic:Patient842').
ex('mammographic:Patient848').
ex('mammographic:Patient851').
ex('mammographic:Patient854').
ex('mammographic:Patient856').
ex('mammographic:Patient858').
ex('mammographic:Patient859').
ex('mammographic:Patient86').
ex('mammographic:Patient860').
ex('mammographic:Patient861').
ex('mammographic:Patient862').
ex('mammographic:Patient863').
ex('mammographic:Patient864').
ex('mammographic:Patient866').
ex('mammographic:Patient870').
ex('mammographic:Patient872').
ex('mammographic:Patient873').
ex('mammographic:Patient878').
ex('mammographic:Patient880').
ex('mammographic:Patient881').
ex('mammographic:Patient883').
ex('mammographic:Patient884').
ex('mammographic:Patient885').
ex('mammographic:Patient887').
ex('mammographic:Patient888').
ex('mammographic:Patient889').
ex('mammographic:Patient89').
ex('mammographic:Patient890').
ex('mammographic:Patient891').
ex('mammographic:Patient892').
ex('mammographic:Patient895').
ex('mammographic:Patient897').
ex('mammographic:Patient899').
ex('mammographic:Patient9').
ex('mammographic:Patient90').
ex('mammographic:Patient900').
ex('mammographic:Patient901').
ex('mammographic:Patient903').
ex('mammographic:Patient904').
ex('mammographic:Patient907').
ex('mammographic:Patient908').
ex('mammographic:Patient91').
ex('mammographic:Patient910').
ex('mammographic:Patient912').
ex('mammographic:Patient914').
ex('mammographic:Patient917').
ex('mammographic:Patient921').
ex('mammographic:Patient923').
ex('mammographic:Patient924').
ex('mammographic:Patient926').
ex('mammographic:Patient928').
ex('mammographic:Patient93').
ex('mammographic:Patient931').
ex('mammographic:Patient935').
ex('mammographic:Patient940').
ex('mammographic:Patient942').
ex('mammographic:Patient944').
ex('mammographic:Patient948').
ex('mammographic:Patient95').
ex('mammographic:Patient950').
ex('mammographic:Patient951').
ex('mammographic:Patient952').
ex('mammographic:Patient955').
ex('mammographic:Patient957').
ex('mammographic:Patient959').
